from errata.notifications.templates.accessor import get_on_accepted_template
from errata.notifications.templates.accessor import get_on_proposed_template
from errata.notifications.templates.accessor import get_on_rejected_template
